apiVersion: batch/v1
kind: Job
metadata:
  name: this-job-run-after-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["/bin/sh","-c"]
        args: ["echo 'post job starting...'; echo 'sleeping...'; sleep 10; echo 'post job finished...'"]
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#next-gen-cicd\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 0
