apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["/bin/sh","-c"]
        args: ["echo 'presync job starting...'; echo 'sleeping...'; sleep 20; echo 'presync job finished...'"]
      restartPolicy: Never
  backoffLimit: 0
